import PREFIXES from '../../actionTypePrefixes'

const NAMESPACE = 'WEATHER_DETAILS'

export const SET_CURRENT_LOCATION = `${NAMESPACE}:SET_CURRENT_LOCATION`
export const CLEAR = `${NAMESPACE}:CLEAR`

export const GET_CURRENT_LOCATION_TRIGGER = `${PREFIXES.TRIGGER}/${NAMESPACE}:GET_CURRENT_LOCATION`
export const GET_CURRENT_LOCATION_REQUEST = `${PREFIXES.REQUEST}/${NAMESPACE}:GET_CURRENT_LOCATION`
export const GET_CURRENT_LOCATION_SUCCESS = `${PREFIXES.SUCCESS}/${NAMESPACE}:GET_CURRENT_LOCATION`
export const GET_CURRENT_LOCATION_FAILURE = `${PREFIXES.FAILURE}/${NAMESPACE}:GET_CURRENT_LOCATION`
export const GET_CURRENT_LOCATION_FULFILL = `${PREFIXES.FULFILL}/${NAMESPACE}:GET_CURRENT_LOCATION`

export const GET_FORECAST_TRIGGER = `${PREFIXES.TRIGGER}/${NAMESPACE}:GET_FORECAST`
export const GET_FORECAST_REQUEST = `${PREFIXES.REQUEST}/${NAMESPACE}:GET_FORECAST`
export const GET_FORECAST_SUCCESS = `${PREFIXES.SUCCESS}/${NAMESPACE}:GET_FORECAST`
export const GET_FORECAST_FAILURE = `${PREFIXES.FAILURE}/${NAMESPACE}:GET_FORECAST`
export const GET_FORECAST_FULFILL = `${PREFIXES.FULFILL}/${NAMESPACE}:GET_FORECAST`

export const GET_CONDITIONS_TRIGGER = `${PREFIXES.TRIGGER}/${NAMESPACE}:GET_CONDITIONS`
export const GET_CONDITIONS_REQUEST = `${PREFIXES.REQUEST}/${NAMESPACE}:GET_CONDITIONS`
export const GET_CONDITIONS_SUCCESS = `${PREFIXES.SUCCESS}/${NAMESPACE}:GET_CONDITIONS`
export const GET_CONDITIONS_FAILURE = `${PREFIXES.FAILURE}/${NAMESPACE}:GET_CONDITIONS`
export const GET_CONDITIONS_FULFILL = `${PREFIXES.FULFILL}/${NAMESPACE}:GET_CONDITIONS`
