import PREFIXES from '../../actionTypePrefixes'

const NAMESPACE = 'FAVORITES'

export const GET_LOCATIONS_CONDITIONS_TRIGGER = `${PREFIXES.TRIGGER}/${NAMESPACE}:GET_LOCATIONS_CONDITIONS`
export const GET_LOCATIONS_CONDITIONS_REQUEST = `${PREFIXES.REQUEST}/${NAMESPACE}:GET_LOCATIONS_CONDITIONS`
export const GET_LOCATIONS_CONDITIONS_SUCCESS = `${PREFIXES.SUCCESS}/${NAMESPACE}:GET_LOCATIONS_CONDITIONS`
export const GET_LOCATIONS_CONDITIONS_FAILURE = `${PREFIXES.FAILURE}/${NAMESPACE}:GET_LOCATIONS_CONDITIONS`
export const GET_LOCATIONS_CONDITIONS_FULFILL = `${PREFIXES.FULFILL}/${NAMESPACE}:GET_LOCATIONS_CONDITIONS`
